
services:
  postgres:
    image: postgres:15
    container_name: viewora_postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: viewora_redis
    ports:
      - "6379:6379"

  backend:
    build: ./Viewora_backend
    container_name: viewora_backend
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    volumes:
      - ./Viewora_backend:/app
      - media_data:/app/media

  celery:
    build: ./Viewora_backend
    container_name: viewora_celery
    command: celery -A viewora_project worker -l info
    depends_on:
      - backend
      - redis
    env_file:
      - .env
    volumes:
      - ./Viewora_backend:/app
  celery_beat:
    build: ./Viewora_backend
    container_name: viewora_celery_beat
    command: celery -A viewora_project beat -l info
    depends_on:
      - redis
      - backend
    env_file:
      - .env
    volumes:
      - ./Viewora_backend:/app


  ai_service:
    build: ./Viewora_ai_service
    container_name: viewora_ai_service
    ports:
      - "8001:8001"
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./Viewora_ai_service:/app
    depends_on:
      - backend

volumes:
  postgres_data:
  media_data:
